export interface SimplifiedHourlyData {
  dtUser: number,
  dateTimeUser?: string,
  dateTextUser?: string,
  hourTextUser?: string,
  dtLocation: number,
  dateTextLocation: string,
  hourTextLocation: string,
  dateMonthName: string,
  dateDayName: string,
  dateLongText: string,
  temp: number,
  tempMin: number,
  tempMax: number,
  tempFeel: number,
  pressure: number,
  description: string,
  icon: string,
  clouds: number,
  windSpeed: number,
  windSpeedKPH: number,
  windDeg: number,
}
